In [2]:
import numpy as np
import plotly.graph_objects as go
import plotly
import pandas as pd
import plotly.offline as py
from scipy.stats import multivariate_normal as g
py.init_notebook_mode(connected=True)

def plot_data(classes, count):
    bar = go.Bar(
        x = classes,
        y = count
    )

    layout = dict(
        title = "Barchart with frequencies",
        xaxis = dict(title = "Classes"),
        xaxis_tickangle = 45
    )

    fig = go.Figure(data = [bar], layout = layout)
    plotly.offline.iplot(fig)

def plot_traintest(classes, train, test):
    bar1 = go.Bar(
        name = "train",
        x = classes,
        y = train
    )

    bar2 = go.Bar(
        name = "test",
        x = classes,
        y = test
    )

    layout = dict(
        title = "Barchart with frequencies",
        xaxis = dict(title = "Classes"),
        xaxis_tickangle = 45
    )

    fig = go.Figure(data = [bar1, bar2], layout = layout)
    plotly.offline.iplot(fig)

# OLD
# def separate_classes(csv_obj,classno):
#     # Separate features for each class in a dictionary, i.e star type
#     classes = {}    #classes contain every feature for each star type

#     for i in range(classno):
#         classes["".join(str(i))] = []
    
#     for row in csv_obj:
#         featdict = {}
#         for feature in row:
#             if feature != "Star type":
#                 featdict[feature] = row[feature]
#         classes[row['Star type']].append(featdict)
    
#     return classes

# def frequencies(clss):
#     # Find frequencies of feature vectors for each class
#     freqs = {}
#     for c in classes:
#        freqs[c] = len(classes[c])
    
#     return freqs

# def pdf(feature, type):
#     # Prepare plots for pdf of each class for selected feature
#     plots = []
#     color = ['(255, 0, 0','(0, 255, 0','(0, 0, 255','(231, 255, 92','(188, 0, 255','(0, 211, 255']

#     for cl in classes:
#         featlist = None
#         if type == 'int': featlist = [int(x[feature]) for x in classes[cl]]
#         elif type == 'float': featlist = [float(x[feature]) for x in classes[cl]]
#         else: featlist = [x[feature] for x in classes[cl]]

#         x1 = np.array(featlist)
#         xspace = np.linspace(x1.min(), x1.max())
#         yspace1 = g.pdf(xspace, mean=x1.mean(),cov=x1.std())

#         cr = color.pop()
#         plots.append(go.Scatter(x=xspace, y=yspace1, name="p(x|y=)".join(cl), marker_color='rgba'+cr+', .9)'))
    
#     return plots

# with open("../6_class_csv.csv","r") as csvf:
#     csvreader = csv.DictReader(csvf)    #read csv as a dictionary
    
#     classes = separate_classes(csvreader,6)
#     freqs = frequencies(classes)
    
#     # Perform GDA
#     # plots = pdf('Temperature (K)', 'int')
#     # layout = go.Layout(title='Star samples GE for p(x|y)', xaxis=dict(title='x'), yaxis=dict(title='p(x|y)'))
#     # fig = go.Figure(data=plots, layout=layout)
#     # plotly.offline.iplot(fig)

#     x1 = np.array([int(x['Temperature (K)']) for x in classes['0']])
#     xspace = np.linspace(x1.min(), x1.max())
#     yspace1 = g.pdf(xspace, mean=x1.mean(),cov=x1.std())

#     fig = go.Figure(data=[
#         go.Scatter(x=xspace, y=yspace1, name="p(x|y=)".join('0'), marker_color='rgba(44, 193, 93, .9)')
#     ])

#     plotly.offline.iplot(fig)

## Preprocess data
Check data structure and clean data by allocating unique and clear classes and text.  
Classes are decribed with natural language, so the class value (e.g "ISTJ") should be extracted from plain text, so ambiguous classes are removed.  
Cases such as "not ISTJ" are not not taken into account for the sake of simplification.

In [3]:
# read csv into dataframe
df = pd.read_csv('../mbti_full_pull.csv')
new_class = []
new_txt = []
classes = ['ISTJ','ISFJ','INFJ','INTJ','ISTP','ISFP','INFP','INTP','ESTP','ESFP','ENFP','ENTP','ESTJ','ESFJ','ENFJ','ENTJ'] # all the classes

print("Size before cleaning: {:d}".format(len(df)))

# extract only the cleaned classes that consist of specific and unique value
for i in range(len(df)):
    txt = df.iloc[i]['author_flair_text']
    uppert = txt.upper()

    count = 0
    clss = ''
    for cl in classes:
        if uppert.find(cl) != -1:
            count += 1
            clss = cl
    if count == 1:
        new_class.append(clss)
        new_txt.append(df.iloc[i]['body'])

mbti = {
    'text': new_txt,
    'class': new_class
}

data = pd.DataFrame(mbti)

data.isnull().sum() # check if null values exist
data = data.dropna() # drop null values (55)

print('Classes cleaned')

print("Size after cleaning: {:d}".format(len(data)))

Size before cleaning: 1794016
Classes cleaned
Size after cleaning: 1782056


## Shrink dataset proportionally

In [4]:
# find class with minimum length
min_length = np.inf
min_class = ''
for v in data['class'].unique():
    lngth = len(data[data['class'] == v])
    if lngth < min_length:
        min_length = lngth
        min_class = v

ratio = []
for v in data['class'].unique():
    ratio.append(len(data[data['class'] == min_class]) / len(data[data['class'] == v]))

# remove (length-remn) items from min class
remn = 200
delindex = data[data['class'] == min_class].index[0:(len(data[data['class'] == min_class]) - remn)]
data.drop(delindex, inplace=True)

#remove items from every other class, retaining the length distribution
for v in data['class'].unique():
    if len(data[data['class'] == v]) == remn: continue
    rt = ratio.pop(0)
    new_size = round(float(remn) / rt)

    delindex = data[data['class'] == v].index[0:(len(data[data['class'] == v]) - new_size)]
    data.drop(delindex, inplace=True)

print("Size after removal: {:d}".format(len(data)))

Size after removal: 129714


## Find imbalanced classes

In [5]:
# observe each class' distribution
freqs = data['class'].value_counts().tolist()
data_classes = data['class'].value_counts().index.tolist()

plot_data(data_classes, freqs)

## Feature extraction
Inspect text and find possible features and relations with Tf-idf  
The vectorizer parameters are tuned in order to find words with max information

In [7]:
from sklearn.feature_extraction import text as fet
import itertools
# find frequency of each word in each text fragment of each row (tfidf: term frequency * inverse document frequency)
# Suggestion: text embeddings with Fasttext, Glove, Word2vec etc.

stopword_list = ['the','a','an','be','am','are','for','of','or','that','this','which','is','then','than','www','youtube','com','reddit','wiki','wikipedia','org']

transformer = fet.TfidfTransformer()
corpus = data['text'].tolist()
vectorizer = fet.CountVectorizer(max_features=100, max_df=0.5, stop_words=stopword_list, ngram_range=(3,3))
# vectorizer = fet.HashingVectorizer(stop_words=stopword_list, ngram_range=(3,3))
counts = vectorizer.fit_transform(corpus)   # count each word in each document

tfidf = transformer.fit_transform(counts) # calculate tfidf by multiplying counts from above with computed idf
# features = vectorizer.get_feature_names()   # features are every counted word in the entire corpus and their values are tfidf's
# print('TfidfTransformer')
# print('----------------')
# print(features)
# print(tfidf.toarray())

In [9]:
# flatten = itertools.chain(*(tfidf.toarray().tolist()))

# # tf idf scatter plot
# scatter = go.Scatter(
#     x = list(flatten),
#     y = list(flatten),
#     mode = 'markers'
# )

# layout = dict(title='Scatterplot of Tf-Idf')
# fgr = go.Figure(data=[scatter], layout=layout)
# plotly.offline.iplot(fgr)

## Feature selection
Bring features and class labels to X, y form, where X is the feature array and y is the class array  
Find correlations among words by selecting the most informative features

In [10]:
from sklearn.feature_selection import SelectKBest, chi2

X = tfidf.toarray()
y = data['class'].to_numpy()

X = SelectKBest(chi2, k=20).fit_transform(X, y) # selecting the k most informative features
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## Split dataset into train and test
Since we have multi-class classification and imbalanced dataset, stratified split should be chosen

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.25)

# plot train and test frequencies
traindict = {
    'features': X_train.tolist(),
    'class': y_train.tolist()
}
trainpd = pd.DataFrame(traindict)
testdict = {
    'features': X_test.tolist(),
    'class': y_test.tolist()
}
testpd = pd.DataFrame(testdict)

freqstrain = trainpd['class'].value_counts().tolist()
freqstest = testpd['class'].value_counts().tolist()
data_classes = trainpd['class'].value_counts().index.tolist()

plot_traintest(data_classes, freqstrain, freqstest)

## Oversampling
The dataset is highly imbalanced and the smallest class has too few data.  
Smote can be used for that case, in order to oversample the training dataset and to balance all classes

In [12]:
from imblearn.over_sampling import SMOTE

oversample = SMOTE()
X_train, y_train = oversample.fit_resample(X_train, y_train)

# plot train frequencies
traindict = {
    'features': X_train.tolist(),
    'class': y_train.tolist()
}
trainpd = pd.DataFrame(traindict)

freqstrain = trainpd['class'].value_counts().tolist()
data_classes = trainpd['class'].value_counts().index.tolist()

plot_data(data_classes, freqstrain)

In [5]:
# save the cleaned dataset to a new csv file
# data.to_csv("./mbti_classes_cleaned.csv")

## Model
Train different binary classifiers using OneVsRest method because we have multi-class classification

In [93]:
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import KFold
from sklearn import metrics

# Split training dataset in 20 folds and keep 1/20 for validation and 19/20 for training
kf = KFold(n_splits=20, shuffle=False, random_state=None)

for train_indx, test_indx in kf.split(X_train):
    Xvalid_train, Xvalid_test = X[train_indx], X[test_indx]
    yvalid_train, yvalid_test = y[train_indx], y[test_indx]

    # fit/predict
    clf = GaussianNB()
    ovr = OneVsRestClassifier(clf)
    ovr.fit(Xvalid_train, yvalid_train)
    ypred = ovr.predict(Xvalid_train)

# clf = GaussianNB()
# ovr = OneVsRestClassifier(clf)
# ovr.fit(X_train, y_train)

0.9378649635036497
